# Generated by Django 4.0.3 on 2022-03-18 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=50, null=True)),
                ('rasmi', models.ImageField(upload_to='images')),
                ('video_link', models.CharField(blank=True, max_length=150)),
                ('narxi', models.FloatField()),
                ('malumot', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=50, null=True)),
                ('rasmi', models.ImageField(upload_to='images')),
                ('video_link', models.CharField(blank=True, max_length=150)),
                ('narxi', models.FloatField()),
                ('malumot', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=150, null=True)),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('nomeri', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(blank=True, max_length=100, null=True)),
                ('rasmi', models.ImageField(upload_to='images')),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
