# Generated by Django 4.0.4 on 2022-05-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingradient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=50, null=True)),
                ('rasmi', models.ImageField(upload_to='images')),
                ('video_link', models.CharField(blank=True, max_length=150)),
                ('narxi', models.FloatField()),
                ('malumot', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
